export { default as Navbar } from './Navbar/Navbar';
export { default as Home } from './Home/Home';
export { default as Products } from './Products/Products';
export { default as News } from './News/News';
export { default as Auth } from './Auth/Auth';
export { default as ProductLink } from './Products/ProductLink/ProductLink';
export { default as Cart } from  './Cart/Cart';
export { default as Profile } from './Profile/Profile';
export { default as Checkout } from './CheckoutForm/Checkout/Checkout';